# Generated by Django 6.0.3 on 2026-03-17 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.LocationMembership', to='core.location'),
        ),
        migrations.AddIndex(
            model_name='locationmembership',
            index=models.Index(fields=['location', 'is_active'], name='accounts_lo_locatio_933c0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='uniq_user_location_membership'),
        ),
    ]
