# Generated by Django 6.0.3 on 2026-03-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='delivery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='location',
            name='delivery_min_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='location',
            name='pickup_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
