# Generated by Django 6.0.3 on 2026-03-17 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('base_unit', models.CharField(max_length=32)),
                ('is_perishable', models.BooleanField(default=False)),
                ('default_low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('target_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delta_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('production_consumption', 'Production Consumption'), ('waste', 'Waste'), ('manual_adjustment', 'Manual Adjustment')], max_length=40)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoodLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_at', models.DateTimeField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_produced', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoodLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delta_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('production', 'Production'), ('sale', 'Sale'), ('waste', 'Waste'), ('manual_adjustment', 'Manual Adjustment')], max_length=40)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=40)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.finishedgoodlot')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('target_stock_level', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12)),
                ('supplier_lot_code', models.CharField(blank=True, max_length=80)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
    ]
