# Generated by Django 6.0.3 on 2026-03-17 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='productdailytarget',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='productdailytarget',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ingredientlot'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodlot',
            index=models.Index(fields=['location', 'product'], name='inventory_f_locatio_0c66ff_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodlot',
            index=models.Index(fields=['expiry_date'], name='inventory_f_expiry__7833c9_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodlot',
            index=models.Index(fields=['location', 'product', 'expiry_date'], name='inventory_f_locatio_065e43_idx'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_produced__gte', 0)), name='fg_lot_qty_produced_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', 0)), name='fg_lot_qty_remaining_nonneg'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodledgerentry',
            index=models.Index(fields=['location', 'product', 'created_at'], name='inventory_f_locatio_6980f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientlocationsettings',
            index=models.Index(fields=['location', 'ingredient'], name='inventory_i_locatio_5c6433_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingredientlocationsettings',
            constraint=models.UniqueConstraint(fields=('location', 'ingredient'), name='uniq_location_ingredient_settings'),
        ),
        migrations.AddIndex(
            model_name='ingredientlot',
            index=models.Index(fields=['location', 'ingredient'], name='inventory_i_locatio_a0b231_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientlot',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__f781b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientlot',
            index=models.Index(fields=['location', 'ingredient', 'expiry_date'], name='inventory_i_locatio_b8ad15_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingredientlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='ingredient_lot_qty_received_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='ingredientlot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__gte', 0)), name='ingredient_lot_qty_remaining_nonneg'),
        ),
        migrations.AddIndex(
            model_name='productdailytarget',
            index=models.Index(fields=['location', 'business_date'], name='inventory_p_locatio_7f6560_idx'),
        ),
        migrations.AddConstraint(
            model_name='productdailytarget',
            constraint=models.UniqueConstraint(fields=('location', 'product', 'business_date'), name='uniq_product_daily_target'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['location', 'ingredient', 'created_at'], name='inventory_s_locatio_165ac0_idx'),
        ),
    ]
