# Generated by Django 6.0.3 on 2026-03-18 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_base_price_product_category_and_more'),
        ('core', '0002_location_delivery_enabled_location_delivery_fee_and_more'),
        ('inventory', '0003_alter_finishedgoodledgerentry_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='storefront__email_6412e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending_payment', max_length=20)),
                ('fulfillment_method', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=20)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_window_start', models.DateTimeField(blank=True, null=True)),
                ('delivery_window_end', models.DateTimeField(blank=True, null=True)),
                ('delivery_address_line1', models.CharField(blank=True, max_length=255)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=255)),
                ('delivery_city', models.CharField(blank=True, max_length=120)),
                ('delivery_state', models.CharField(blank=True, max_length=80)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=32)),
                ('delivery_country', models.CharField(blank=True, max_length=2)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storefront.storecustomer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='storefront.storeorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrderReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('consumed', 'Consumed')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_good_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.finishedgoodlot')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.finishedgoodledgerentry')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='storefront.storeorderline')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='storefront.storeorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['location', 'created_at'], name='storefront__locatio_841c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['status', 'created_at'], name='storefront__status_0705e8_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorderline',
            index=models.Index(fields=['order'], name='storefront__order_i_8b46bb_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorderreservation',
            index=models.Index(fields=['order', 'status'], name='storefront__order_i_32306a_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeorderreservation',
            constraint=models.UniqueConstraint(fields=('order', 'line', 'finished_good_lot'), name='uniq_store_order_reservation'),
        ),
    ]
