# Generated by Django 6.0.3 on 2026-03-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0001_initial'),
        ('inventory', '0002_initial'),
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['location', 'kind', 'is_active', 'last_seen_at'], name='notificatio_locatio_624044_idx'),
        ),
    ]
